In [1]:
#import dependencies
import os
import csv
import pandas as pd

In [2]:
# Path to collect data from the Resources folder

#1 - Worldwide COVID-19 Data

file_path = os.path.join('..', 'Resources', 'Ourworlddata_Covid_19_worldwide_data_set.csv')

# Import the Ourworlddata_Covid_19_worldwide_data_set.csv file as a DataFrame
covid_ww_df=pd.read_csv(file_path)

covid_ww_df.head(5)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,ABW,North America,Aruba,2020-03-13,2.0,2.0,NaN,NaN,0.0,NaN,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
1,ABW,North America,Aruba,2020-03-19,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
2,ABW,North America,Aruba,2020-03-20,4.0,2.0,0.286,NaN,0.0,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
3,ABW,North America,Aruba,2020-03-21,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
4,ABW,North America,Aruba,2020-03-22,NaN,NaN,0.286,NaN,NaN,0.0,...,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN

In [3]:
#Summary Statistics

covid_ww_df.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
count,5.075600e+04,53469.000000,52669.000000,4.166700e+04,53469.000000,52669.000000,50483.000000,53405.000000,52604.000000,41409.000000,...,47769.000000,31842.000000,48380.000000,50143.000000,37694.000000,37209.000000,22853.000000,43604.000000,53388.000000,46705.000000
mean,1.493619e+05,1761.487572,1732.743639,6.447778e+03,45.156184,45.137385,2759.791429,33.925591,32.953985,89.419042,...,20702.018949,12.354896,252.260040,8.060757,10.761713,32.642931,52.187253,3.094716,73.961717,0.722943
std,1.499361e+06,16084.465899,15678.575064,5.229041e+04,374.862461,364.309001,5431.255524,119.552191,86.228298,173.933620,...,20344.678674,19.377857,117.426237,4.167827,10.473784,13.446463,31.636330,2.516902,7.392559,0.153174
min,1.000000e+00,-8261.000000,-552.000000,1.000000e+00,-1918.000000,-232.143000,0.001000,-2212.545000,-269.978000,0.000000,...,661.240000,0.100000,79.370000,0.990000,0.100000,7.700000,1.188000,0.100000,53.280000,0.354000
25%,1.550000e+02,0.000000,0.714000,1.200000e+01,0.000000,0.000000,80.807500,0.000000,0.226000,3.653000,...,5321.444000,0.500000,156.139000,5.310000,1.900000,21.400000,21.222000,1.300000,69.870000,0.601000
50%,1.884500e+03,13.000000,18.143000,7.800000e+01,0.000000,0.286000,528.783000,2.015000,3.640000,19.020000,...,14048.881000,2.000000,238.339000,7.110000,6.400000,31.400000,52.232000,2.500000,75.400000,0.752000
75%,1.913900e+04,212.000000,220.857000,6.570000e+02,3.000000,3.714000,3081.251000,23.635000,26.700750,78.833000,...,31400.840000,18.100000,318.991000,10.390000,19.600000,40.900000,83.741000,4.200000,79.380000,0.847000
max,4.709322e+07,547141.000000,492851.000000,1.207290e+06,10491.000000,7456.857000,63262.797000,8652.658000,2472.188000,1237.551000,...,116935.600000,77.600000,724.417000,30.530000,44.000000,78.100000,98.999000,13.800000,86.750000,0.953000

In [4]:
# Finding how many unique locations are provided
covid_ww_df["location"].unique() #value_counts()

array(['Aruba', 'Afghanistan', 'Angola', 'Anguilla', 'Albania', 'Andorra',
       'United Arab Emirates', 'Argentina', 'Armenia',
       'Antigua and Barbuda', 'Australia', 'Austria', 'Azerbaijan',
       'Burundi', 'Belgium', 'Benin', 'Bonaire Sint Eustatius and Saba',
       'Burkina Faso', 'Bangladesh', 'Bulgaria', 'Bahrain', 'Bahamas',
       'Bosnia and Herzegovina', 'Belarus', 'Belize', 'Bermuda',
       'Bolivia', 'Brazil', 'Barbados', 'Brunei', 'Bhutan', 'Botswana',
       'Central African Republic', 'Canada', 'Switzerland', 'Chile',
       'China', "Cote d'Ivoire", 'Cameroon',
       'Democratic Republic of Congo', 'Congo', 'Colombia', 'Comoros',
       'Cape Verde', 'Costa Rica', 'Cuba', 'Curacao', 'Cayman Islands',
       'Cyprus', 'Czech Republic', 'Germany', 'Djibouti', 'Dominica',
       'Denmark', 'Dominican Republic', 'Algeria', 'Ecuador', 'Egypt',
       'Eritrea', 'Western Sahara', 'Spain', 'Estonia', 'Ethiopia',
       'Finland', 'Fiji', 'Falkland Islands', 'France', 'Faeroe Islands',
       'Gabon', 'United Kingdom', 'Georgia', 'Guernsey', 'Ghana',
       'Gibraltar', 'Guinea', 'Gambia', 'Guinea-Bissau',
       'Equatorial Guinea', 'Greece', 'Grenada', 'Greenland', 'Guatemala',
       'Guam', 'Guyana', 'Hong Kong', 'Honduras', 'Croatia', 'Haiti',
       'Hungary', 'Indonesia', 'Isle of Man', 'India', 'Ireland', 'Iran',
       'Iraq', 'Iceland', 'Israel', 'Italy', 'Jamaica', 'Jersey',
       'Jordan', 'Japan', 'Kazakhstan', 'Kenya', 'Kyrgyzstan', 'Cambodia',
       'Saint Kitts and Nevis', 'South Korea', 'Kuwait', 'Laos',
       'Lebanon', 'Liberia', 'Libya', 'Saint Lucia', 'Liechtenstein',
       'Sri Lanka', 'Lesotho', 'Lithuania', 'Luxembourg', 'Latvia',
       'Morocco', 'Monaco', 'Moldova', 'Madagascar', 'Maldives', 'Mexico',
       'Marshall Islands', 'Macedonia', 'Mali', 'Malta', 'Myanmar',
       'Montenegro', 'Mongolia', 'Northern Mariana Islands', 'Mozambique',
       'Mauritania', 'Montserrat', 'Mauritius', 'Malawi', 'Malaysia',
       'Namibia', 'New Caledonia', 'Niger', 'Nigeria', 'Nicaragua',
       'Netherlands', 'Norway', 'Nepal', 'New Zealand', 'Oman',
       'Pakistan', 'Panama', 'Peru', 'Philippines', 'Papua New Guinea',
       'Poland', 'Puerto Rico', 'Portugal', 'Paraguay', 'Palestine',
       'French Polynesia', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saudi Arabia', 'Sudan', 'Senegal', 'Singapore', 'Solomon Islands',
       'Sierra Leone', 'El Salvador', 'San Marino', 'Somalia', 'Serbia',
       'South Sudan', 'Sao Tome and Principe', 'Suriname', 'Slovakia',
       'Slovenia', 'Sweden', 'Swaziland', 'Sint Maarten (Dutch part)',
       'Seychelles', 'Syria', 'Turks and Caicos Islands', 'Chad', 'Togo',
       'Thailand', 'Tajikistan', 'Timor', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Taiwan', 'Tanzania', 'Uganda', 'Ukraine',
       'Uruguay', 'United States', 'Uzbekistan', 'Vatican',
       'Saint Vincent and the Grenadines', 'Venezuela',
       'British Virgin Islands', 'United States Virgin Islands',
       'Vietnam', 'Wallis and Futuna', 'Kosovo', 'Yemen', 'South Africa',
       'Zambia', 'Zimbabwe', 'World', 'International'], dtype=object)

In [5]:
#### new cases by location for each date (graph may provide insight)

In [8]:
##create a subset of the world wide data
columns = ["iso_code","continent","location",'stringency_index','population','population_density','median_age','gdp_per_capita','extreme_poverty','cardiovasc_death_rate','diabetes_prevalence','female_smokers','male_smokers','handwashing_facilities','hospital_beds_per_thousand','life_expectancy','human_development_index']

country_info_pd=covid_ww_df[columns]

country_info_pd.head()

,iso_code,continent,location,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,ABW,North America,Aruba,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
1,ABW,North America,Aruba,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
2,ABW,North America,Aruba,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
3,ABW,North America,Aruba,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN
4,ABW,North America,Aruba,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN,76.29,NaN

In [10]:
country_grp= country_info_pd.groupby("location").mean()
country_grp

,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
location,,,,,,,,,,
Afghanistan,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.500,64.83,0.498
Albania,11803.431,1.1,304.195,10.08,7.100,51.200,NaN,2.890,78.57,0.785
Algeria,13913.839,0.5,278.364,6.73,0.700,30.400,83.741,1.900,76.88,0.754
Andorra,NaN,NaN,109.135,7.97,29.000,37.800,NaN,NaN,83.73,0.858
Angola,5819.495,NaN,276.045,3.94,NaN,NaN,26.664,NaN,61.15,0.581
...,...,...,...,...,...,...,...,...,...,...
Western Sahara,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.26,NaN
World,15469.207,10.0,233.070,8.51,6.434,34.635,60.130,2.705,72.58,NaN
Yemen,1479.147,18.8,495.003,5.35,7.600,29.200,49.542,0.700,66.12,0.452
Zambia,3689.251,57.5,234.499,3.94,3.100,24.700,13.938,2.000,63.89,0.588
Zimbabwe,1899.775,21.4,307.846,1.82,1.600,30.700,36.791,1.700,61.49,0.535

In [ ]:
### To Do: merge country_grp with the covid-metrics by date in columns or total cases etc?

In [26]:
#Group COVID Data by Country and Date

covid_grp_df= covid_ww_df.groupby(['location','date']).agg({"total_cases":'max',
                                                   "new_cases":'max',
                                                   #"new_cases_smoothed":'mean',
                                                   "total_deaths":'max',
                                                   "new_deaths": 'max',
                                                   "new_deaths_smoothed":'max',
                                                   "total_cases_per_million": 'max',
                                                   "new_cases_per_million": 'max',
                                                   "new_cases_smoothed_per_million": 'max',
                                                   "total_deaths_per_million": 'max',
                                                   "new_deaths_per_million": 'max',
                                                   "new_deaths_smoothed_per_million": 'max',
                                                   "icu_patients": 'max',
                                                   "icu_patients_per_million": 'max',
                                                   "weekly_icu_admissions": 'max',
                                                   "weekly_icu_admissions_per_million": 'max',
                                                   "weekly_hosp_admissions": 'max',
                                                   "weekly_hosp_admissions_per_million": 'max',
                                                   "total_tests": 'max',
                                                   "new_tests": 'max',
                                                   "total_tests_per_thousand": 'max',
                                                   "new_tests_per_thousand": 'max',
                                                   "new_tests_smoothed": 'max',
                                                   "new_tests_smoothed_per_thousand": 'max',
                                                   "tests_per_case": 'max',
                                                   "positive_rate": 'max',
                                                
                                                  })

covid_grp_df

                        total_cases  new_cases  total_deaths  new_deaths  \
location    date
Afghanistan 2019-12-31          NaN        0.0           NaN         0.0
            2020-01-01          NaN        0.0           NaN         0.0
            2020-01-02          NaN        0.0           NaN         0.0
            2020-01-03          NaN        0.0           NaN         0.0
            2020-01-04          NaN        0.0           NaN         0.0
...                             ...        ...           ...         ...
Zimbabwe    2020-10-30       8349.0       29.0         242.0         0.0
            2020-10-31       8362.0       13.0         242.0         0.0
            2020-11-01       8362.0        0.0         242.0         0.0
            2020-11-02       8374.0       12.0         243.0         1.0
            2020-11-03       8389.0       15.0         245.0         2.0

                        new_deaths_smoothed  total_cases_per_million  \
location    date
Afghanistan 2019-12-31                  NaN                      NaN
            2020-01-01                  NaN                      NaN
            2020-01-02                  NaN                      NaN
            2020-01-03                  NaN                      NaN
            2020-01-04                  NaN                      NaN
...                                     ...                      ...
Zimbabwe    2020-10-30                0.857                  561.733
            2020-10-31                0.857                  562.608
            2020-11-01                0.857                  562.608
            2020-11-02                0.857                  563.415
            2020-11-03                0.429                  564.424

                        new_cases_per_million  new_cases_smoothed_per_million  \
location    date
Afghanistan 2019-12-31                  0.000                             NaN
            2020-01-01                  0.000                             NaN
            2020-01-02                  0.000                             NaN
            2020-01-03                  0.000                             NaN
            2020-01-04                  0.000                             NaN
...                                       ...                             ...
Zimbabwe    2020-10-30                  1.951                           1.028
            2020-10-31                  0.875                           1.009
            2020-11-01                  0.000                           0.894
            2020-11-02                  0.807                           0.942
            2020-11-03                  1.009                           0.827

                        total_deaths_per_million  new_deaths_per_million  ...  \
location    date                                                          ...
Afghanistan 2019-12-31                       NaN                   0.000  ...
            2020-01-01                       NaN                   0.000  ...
            2020-01-02                       NaN                   0.000  ...
            2020-01-03                       NaN                   0.000  ...
            2020-01-04                       NaN                   0.000  ...
...                                          ...                     ...  ...
Zimbabwe    2020-10-30                    16.282                   0.000  ...
            2020-10-31                    16.282                   0.000  ...
            2020-11-01                    16.282                   0.000  ...
            2020-11-02                    16.349                   0.067  ...
            2020-11-03                    16.484                   0.135  ...

                        weekly_hosp_admissions  \
location    date
Afghanistan 2019-12-31                     NaN
            2020-01-01                     NaN
            2020-01-02                     NaN
            2020-01-03                     NaN
            2020-01-04                     NaN
...                                        ...
Zimbabwe    2020-10-30                     NaN
            2020-10-31                     NaN
            2020-11-01                     NaN
            2020-11-02                     NaN
            2020-11-03                     NaN

                        weekly_hosp_admissions_per_million  total_tests  \
location    date
Afghanistan 2019-12-31                                 NaN          NaN
            2020-01-01                                 NaN          NaN
            2020-01-02                                 NaN          NaN
            2020-01-03                                 NaN          NaN
            2020-01-04                                 NaN          NaN
...                                                    ...          ...
Zimbabwe    2020-10-30                                 NaN     140725.0
            2020-10-31                                 NaN     141406.0
            2020-11-01                                 NaN     141980.0
            2020-11-02                                 NaN          NaN
            2020-11-03                                 NaN          NaN

                        new_tests  total_tests_per_thousand  \
location    date
Afghanistan 2019-12-31        NaN                       NaN
            2020-01-01        NaN                       NaN
            2020-01-02        NaN                       NaN
            2020-01-03        NaN                       NaN
            2020-01-04        NaN                       NaN
...                           ...                       ...
Zimbabwe    2020-10-30      911.0                     9.468
            2020-10-31      681.0                     9.514
            2020-11-01      574.0                     9.553
            2020-11-02        NaN                       NaN
            2020-11-03        NaN                       NaN

                        new_tests_per_thousand  new_tests_smoothed  \
location    date
Afghanistan 2019-12-31                     NaN                 NaN
            2020-01-01                     NaN                 NaN
            2020-01-02                     NaN                 NaN
            2020-01-03                     NaN                 NaN
            2020-01-04                     NaN                 NaN
...                                        ...                 ...
Zimbabwe    2020-10-30                   0.061               831.0
            2020-10-31                   0.046               839.0
            2020-11-01                   0.039               804.0
            2020-11-02                     NaN                 NaN
            2020-11-03                     NaN                 NaN

                        new_tests_smoothed_per_thousand  tests_per_case  \
location    date
Afghanistan 2019-12-31                              NaN             NaN
            2020-01-01                              NaN             NaN
            2020-01-02                              NaN             NaN
            2020-01-03                              NaN             NaN
            2020-01-04                              NaN             NaN
...                                                 ...             ...
Zimbabwe    2020-10-30                            0.056          54.364
            2020-10-31                            0.056          55.933
            2020-11-01                            0.054          60.516
            2020-11-02                              NaN             NaN
            2020-11-03                              NaN             NaN

                        positive_rate
location    date
Afghanistan 2019-12-31            NaN
            2020-01-01            NaN
            2020-01-02            NaN
            2020-01-03            NaN
            2020-01-04            NaN
...                               ...
Zimbabwe    2020-10-30          0.018
            2020-10-31          0.018
            2020-11-01          0.017
            2020-11-02            NaN
            2020-11-03            NaN

[54390 rows x 25 columns]

In [28]:
#Group COVID Data by Country only

covid_grp2_df= covid_ww_df.groupby(['location']).agg({"total_cases":'max',
                                                   "new_cases":'max',
                                                   #"new_cases_smoothed":'mean',
                                                   "total_deaths":'max',
                                                   "new_deaths": 'max',
                                                   "new_deaths_smoothed":'max',
                                                   "total_cases_per_million": 'max',
                                                   "new_cases_per_million": 'max',
                                                   "new_cases_smoothed_per_million": 'max',
                                                   "total_deaths_per_million": 'max',
                                                   "new_deaths_per_million": 'max',
                                                   "new_deaths_smoothed_per_million": 'max',
                                                   "icu_patients": 'max',
                                                   "icu_patients_per_million": 'max',
                                                   "weekly_icu_admissions": 'max',
                                                   "weekly_icu_admissions_per_million": 'max',
                                                   "weekly_hosp_admissions": 'max',
                                                   "weekly_hosp_admissions_per_million": 'max',
                                                   "total_tests": 'max',
                                                   "new_tests": 'max',
                                                   "total_tests_per_thousand": 'max',
                                                   "new_tests_per_thousand": 'max',
                                                   "new_tests_smoothed": 'max',
                                                   "new_tests_smoothed_per_thousand": 'max',
                                                   "tests_per_case": 'max',
                                                   "positive_rate": 'max',
                                                
                                                  })

covid_grp2_df

,total_cases,new_cases,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,...,weekly_hosp_admissions,weekly_hosp_admissions_per_million,total_tests,new_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,tests_per_case,positive_rate
location,,,,,,,,,,,,,,,,,,,,,
Afghanistan,41728.0,1063.0,1544.0,56.0,27.143,1071.918,27.307,19.486,39.663,1.439,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Albania,21523.0,327.0,527.0,9.0,6.714,7478.977,113.628,104.346,183.126,3.127,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Algeria,58574.0,675.0,1980.0,42.0,24.571,1335.749,15.393,14.194,45.153,0.958,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,4888.0,299.0,75.0,6.0,2.000,63262.797,3869.799,1455.103,970.685,77.655,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Angola,11035.0,355.0,286.0,13.0,4.571,335.755,10.801,7.920,8.702,0.396,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Western Sahara,766.0,242.0,1.0,1.0,0.143,1282.373,405.136,118.145,1.674,1.674,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
World,47093222.0,547141.0,1207290.0,10491.0,7456.857,6041.621,70.193,63.228,154.884,1.346,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yemen,2063.0,116.0,600.0,52.0,16.429,69.168,3.889,1.748,20.117,1.743,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zambia,16543.0,527.0,349.0,40.0,11.143,899.861,28.666,16.373,18.984,2.176,...,NaN,NaN,275011.0,6843.0,14.959,0.372,4819.0,0.262,560.0,0.293
Zimbabwe,8389.0,490.0,245.0,18.0,6.714,564.424,32.968,14.033,16.484,1.211,...,NaN,NaN,141980.0,5055.0,9.553,0.340,2039.0,0.137,1127.0,0.178