In [1]:
#import dependencies
import os
import csv
import pandas as pd

In [2]:
# Path to collect data from the Resources folder

#1 - Death Counts for Infections - Influenza, Pnuemonia, COVID-19

file_path = os.path.join('..', 'Resources', 'Death_Counts_for_infections_Influenza__Pneumonia__and_COVID-19.csv')

# Import the Death_Counts_for_infections_Influenza__Pneumonia__and_COVID-19.csv file as a DataFrame
death_counts_df=pd.read_csv(file_path)

death_counts_df.head(5)

,Data As Of,Start Week,End Week,MMWRyear,MMWRweek,Group,Indicator,Jurisdiction,Age Group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Influenza Deaths,Pneumonia or Influenza,"Pneumonia, Influenza, or COVID-19 Deaths",Footnote
0,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,United States,All Ages,0.0,58486.0,3789.0,478.0,4267.0,4267.0,NaN
1,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,United States,0-17 years,0.0,652.0,12.0,16.0,28.0,28.0,NaN
2,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,United States,18-64 years,0.0,13994.0,700.0,184.0,884.0,884.0,NaN
3,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,United States,65+ years,0.0,43840.0,3077.0,278.0,3355.0,3355.0,NaN
4,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,Alabama,All Ages,0.0,1055.0,55.0,16.0,71.0,71.0,NaN

In [3]:
#Summary Statistics

death_counts_df.describe()

## shows cases where cells are blank
## investigate: 
######## where One or more data cells have counts between 1-9
######## and have been suppressed in accordance with NCHS confidentiality standards.

###Cleansing Assumption: ???

,MMWRyear,MMWRweek,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Influenza Deaths,Pneumonia or Influenza,"Pneumonia, Influenza, or COVID-19 Deaths"
count,9828.0,9828.000000,8204.000000,8809.000000,8064.000000,7571.000000,8044.000000,8193.000000
mean,2020.0,24.000000,154.804851,1589.796912,161.552951,4.497556,166.974515,248.267668
std,0.0,11.255201,719.894200,5320.650575,582.938225,29.227457,599.098948,965.397469
min,2020.0,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2020.0,14.000000,0.000000,88.000000,0.000000,0.000000,0.000000,10.000000
50%,2020.0,24.000000,11.000000,388.000000,32.000000,0.000000,34.000000,43.000000
75%,2020.0,34.000000,70.000000,1204.000000,104.250000,0.000000,109.000000,151.000000
max,2020.0,43.000000,17059.000000,78793.000000,11960.000000,653.000000,12432.000000,21211.000000

In [4]:
# Finding how many unique Jurisdictions are provided
death_counts_df["Jurisdiction"].unique() ##value_counts()

####  HHS Regions: https://www.hhs.gov/about/agencies/iea/regional-offices/index.html
### exclude since we cannot aggregate with other datasources

array(['United States', 'Alabama', 'Alaska', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
       'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
       'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'New York City', 'North Carolina', 'North Dakota', 'Ohio',
       'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin',
       'Wyoming', 'HHS Region 1', 'HHS Region 2', 'HHS Region 3',
       'HHS Region 4', 'HHS Region 5', 'HHS Region 6', 'HHS Region 7',
       'HHS Region 8', 'HHS Region 9', 'HHS Region 10'], dtype=object)

In [5]:
##remove HHS Regions from data
clean_df = death_counts_df[~death_counts_df["Jurisdiction"].str.contains('HHS Region')] 
clean_df["Jurisdiction"].unique()

array(['United States', 'Alabama', 'Alaska', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
       'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
       'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'New York City', 'North Carolina', 'North Dakota', 'Ohio',
       'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin',
       'Wyoming'], dtype=object)

In [6]:
clean_df.describe()

,MMWRyear,MMWRweek,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Influenza Deaths,Pneumonia or Influenza,"Pneumonia, Influenza, or COVID-19 Deaths"
count,8268.0,8268.000000,6805.000000,7256.000000,6707.000000,6477.000000,6699.000000,6868.000000
mean,2020.0,24.000000,124.180602,1286.515711,129.218279,3.373784,133.406926,197.243157
std,0.0,11.255309,723.024378,5604.098882,601.657585,29.427364,617.890254,983.893028
min,2020.0,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2020.0,14.000000,0.000000,74.000000,0.000000,0.000000,0.000000,0.000000
50%,2020.0,24.000000,0.000000,306.500000,25.000000,0.000000,26.000000,33.000000
75%,2020.0,34.000000,50.000000,904.250000,77.000000,0.000000,80.000000,106.000000
max,2020.0,43.000000,17059.000000,78793.000000,11960.000000,653.000000,12432.000000,21211.000000

In [7]:
clean_df2=clean_df[clean_df["Age Group"]!="All Ages"]
clean_df2

,Data As Of,Start Week,End Week,MMWRyear,MMWRweek,Group,Indicator,Jurisdiction,Age Group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Influenza Deaths,Pneumonia or Influenza,"Pneumonia, Influenza, or COVID-19 Deaths",Footnote
1,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,United States,0-17 years,0.0,652.0,12.0,16.0,28.0,28.0,NaN
2,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,United States,18-64 years,0.0,13994.0,700.0,184.0,884.0,884.0,NaN
3,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,United States,65+ years,0.0,43840.0,3077.0,278.0,3355.0,3355.0,NaN
5,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,Alabama,0-17 years,0.0,24.0,NaN,NaN,NaN,NaN,One or more data cells have counts between 1-9...
6,10/29/2020,02/01/2020,02/01/2020,2020,5,By week,Week-ending,Alabama,18-64 years,0.0,275.0,15.0,NaN,23.0,23.0,One or more data cells have counts between 1-9...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9782,10/29/2020,10/24/2020,10/24/2020,2020,43,By week,Week-ending,Wisconsin,18-64 years,NaN,89.0,NaN,0.0,NaN,NaN,One or more data cells have counts between 1-9...
9783,10/29/2020,10/24/2020,10/24/2020,2020,43,By week,Week-ending,Wisconsin,65+ years,53.0,425.0,35.0,0.0,35.0,68.0,NaN
9785,10/29/2020,10/24/2020,10/24/2020,2020,43,By week,Week-ending,Wyoming,0-17 years,0.0,0.0,0.0,0.0,0.0,0.0,NaN
9786,10/29/2020,10/24/2020,10/24/2020,2020,43,By week,Week-ending,Wyoming,18-64 years,0.0,NaN,0.0,0.0,0.0,0.0,One or more data cells have counts between 1-9...
9787,10/29/2020,10/24/2020,10/24/2020,2020,43,By week,Week-ending,Wyoming,65+ years,NaN,39.0,NaN,0.0,NaN,NaN,One or more data cells have counts between 1-9...

In [8]:
#Group by Jurisdiction and Age Group - mean of remaining columns
age_grp1_df=clean_df2.groupby(['Jurisdiction', 'Age Group']).mean()
age_grp1_df
age_grp1_df=age_grp1_df.rename(
    columns= {'COVID-19 Deaths':"Average COVID-19 Deaths",
              'Total Deaths':"Average Total Deaths",
              "Pneumonia Deaths":"Average Pneumonia Deaths",
              "Influenza Deaths":"Average Influenza Deaths",
              "Pneumonia or Influenza":"Average Pneumonia or Influenza",
              "Pneumonia, Influenza, or COVID-19 Deaths":"Average Pneumonia, Influenza, or COVID-19 Deaths"         
            })
age_grp1_df.head(5)

                          MMWRyear  MMWRweek  Average COVID-19 Deaths  \
Jurisdiction Age Group
Alabama      0-17 years       2020        24                 0.000000
             18-64 years      2020        24                24.054054
             65+ years        2020        24                80.342105
Alaska       0-17 years       2020        24                 0.000000
             18-64 years      2020        24                 0.000000

                          Average Total Deaths  Average Pneumonia Deaths  \
Jurisdiction Age Group
Alabama      0-17 years              13.107143                  0.000000
             18-64 years            318.743590                 22.594595
             65+ years              812.076923                 69.512821
Alaska       0-17 years               0.000000                  0.000000
             18-64 years             31.135135                  0.000000

                          Average Influenza Deaths  \
Jurisdiction Age Group
Alabama      0-17 years                   0.000000
             18-64 years                  0.392857
             65+ years                    0.000000
Alaska       0-17 years                   0.000000
             18-64 years                  0.000000

                          Average Pneumonia or Influenza  \
Jurisdiction Age Group
Alabama      0-17 years                         0.000000
             18-64 years                       23.945946
             65+ years                         70.923077
Alaska       0-17 years                         0.000000
             18-64 years                        0.000000

                          Average Pneumonia, Influenza, or COVID-19 Deaths
Jurisdiction Age Group
Alabama      0-17 years                                           0.000000
             18-64 years                                         39.657895
             65+ years                                          122.102564
Alaska       0-17 years                                           0.000000
             18-64 years                                          0.000000

In [9]:
#Group by Jurisdiction and Age Group - sum of remaining columns
age_grp2_df=clean_df2.groupby(['Jurisdiction', 'Age Group']).sum()
age_grp2_df.head(5)

                          MMWRyear  MMWRweek  COVID-19 Deaths  Total Deaths  \
Jurisdiction Age Group
Alabama      0-17 years      78780       936              0.0         367.0
             18-64 years     78780       936            890.0       12431.0
             65+ years       78780       936           3053.0       31671.0
Alaska       0-17 years      78780       936              0.0           0.0
             18-64 years     78780       936              0.0        1152.0

                          Pneumonia Deaths  Influenza Deaths  \
Jurisdiction Age Group
Alabama      0-17 years                0.0               0.0
             18-64 years             836.0              11.0
             65+ years              2711.0               0.0
Alaska       0-17 years                0.0               0.0
             18-64 years               0.0               0.0

                          Pneumonia or Influenza  \
Jurisdiction Age Group
Alabama      0-17 years                      0.0
             18-64 years                   886.0
             65+ years                    2766.0
Alaska       0-17 years                      0.0
             18-64 years                     0.0

                          Pneumonia, Influenza, or COVID-19 Deaths
Jurisdiction Age Group
Alabama      0-17 years                                        0.0
             18-64 years                                    1507.0
             65+ years                                      4762.0
Alaska       0-17 years                                        0.0
             18-64 years                                       0.0

In [10]:
#Group by Jurisdiction  - mean of remaining columns
age_grp3_df=clean_df2.groupby(['Jurisdiction']).mean()
age_grp3_df=age_grp3_df.rename(
    columns= {'COVID-19 Deaths':"Average COVID-19 Deaths",
              'Total Deaths':"Average Total Deaths",
              "Pneumonia Deaths":"Average Pneumonia Deaths",
              "Influenza Deaths":"Average Influenza Deaths",
              "Pneumonia or Influenza":"Average Pneumonia or Influenza",
              "Pneumonia, Influenza, or COVID-19 Deaths":"Average Pneumonia, Influenza, or COVID-19 Deaths"         
            })
age_grp3_df.head(5)

,MMWRyear,MMWRweek,Average COVID-19 Deaths,Average Total Deaths,Average Pneumonia Deaths,Average Influenza Deaths,Average Pneumonia or Influenza,"Average Pneumonia, Influenza, or COVID-19 Deaths"
Jurisdiction,,,,,,,,
Alabama,2020,24,34.893805,419.518868,32.245455,0.129412,33.200000,56.990909
Alaska,2020,24,0.000000,39.185185,0.000000,0.000000,0.000000,0.000000
Arizona,2020,24,47.596330,470.324561,51.831776,0.137931,53.819048,76.057692
Arkansas,2020,24,16.150000,289.100000,21.650485,0.111111,22.533981,30.523364
California,2020,24,156.775701,1896.655172,234.821053,5.802198,243.319149,325.290323

In [11]:
#Group by Jurisdiction  - sum of remaining columns
age_grp4_df=clean_df2.groupby(['Jurisdiction']).sum()
age_grp4_df.head(5)

,MMWRyear,MMWRweek,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Influenza Deaths,Pneumonia or Influenza,"Pneumonia, Influenza, or COVID-19 Deaths"
Jurisdiction,,,,,,,,
Alabama,236340,2808,3943.0,44469.0,3547.0,11.0,3652.0,6269.0
Alaska,236340,2808,0.0,3174.0,0.0,0.0,0.0,0.0
Arizona,236340,2808,5188.0,53617.0,5546.0,12.0,5651.0,7910.0
Arkansas,236340,2808,1615.0,26019.0,2230.0,10.0,2321.0,3266.0
California,236340,2808,16775.0,220012.0,22308.0,528.0,22872.0,30252.0

In [12]:
#Group by Age Group  - mean of remaining columns
age_grp5_df=clean_df2.groupby(['Jurisdiction']).mean()
age_grp5_df=age_grp5_df.rename(
    columns= {'COVID-19 Deaths':"Average COVID-19 Deaths",
              'Total Deaths':"Average Total Deaths",
              "Pneumonia Deaths":"Average Pneumonia Deaths",
              "Influenza Deaths":"Average Influenza Deaths",
              "Pneumonia or Influenza":"Average Pneumonia or Influenza",
              "Pneumonia, Influenza, or COVID-19 Deaths":"Average Pneumonia, Influenza, or COVID-19 Deaths"         
            })
age_grp5_df.head(5)

,MMWRyear,MMWRweek,Average COVID-19 Deaths,Average Total Deaths,Average Pneumonia Deaths,Average Influenza Deaths,Average Pneumonia or Influenza,"Average Pneumonia, Influenza, or COVID-19 Deaths"
Jurisdiction,,,,,,,,
Alabama,2020,24,34.893805,419.518868,32.245455,0.129412,33.200000,56.990909
Alaska,2020,24,0.000000,39.185185,0.000000,0.000000,0.000000,0.000000
Arizona,2020,24,47.596330,470.324561,51.831776,0.137931,53.819048,76.057692
Arkansas,2020,24,16.150000,289.100000,21.650485,0.111111,22.533981,30.523364
California,2020,24,156.775701,1896.655172,234.821053,5.802198,243.319149,325.290323

In [13]:

#Group by Age Group  - sum of remaining columns
age_grp6_df=clean_df2.groupby(['Jurisdiction']).sum()
age_grp6_df.head(5)

,MMWRyear,MMWRweek,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Influenza Deaths,Pneumonia or Influenza,"Pneumonia, Influenza, or COVID-19 Deaths"
Jurisdiction,,,,,,,,
Alabama,236340,2808,3943.0,44469.0,3547.0,11.0,3652.0,6269.0
Alaska,236340,2808,0.0,3174.0,0.0,0.0,0.0,0.0
Arizona,236340,2808,5188.0,53617.0,5546.0,12.0,5651.0,7910.0
Arkansas,236340,2808,1615.0,26019.0,2230.0,10.0,2321.0,3266.0
California,236340,2808,16775.0,220012.0,22308.0,528.0,22872.0,30252.0